# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firstname',
            field=models.CharField(default='sagar', max_length=10),
        ),
    ]
